## Zola stuff
## Customize these as you see fit, unless otherwise specified.
base_url = "https://anemone.pages.dev"
description = "A minimalist Zola theme that prioritizes clean CSS and avoids heavy JavaScript. Enjoy a seamless user experience with lightning-fast load times. Let your content take center stage in a clutter-free, elegant design that enhances readability. Responsive and efficient, anemone brings focus to your ideas."
compile_sass = false
generate_feeds = true
default_language = "en"

# IMPORTANT! Keep this disabled: HTML minifying currently breaks our CSS!
# We use CSS in <style> blocks to allow configuring colors from here.
# Until https://github.com/getzola/zola/pull/2242 is merged, there likely
# won't be a cleaner way to achieve this.
minify_html = false

taxonomies = [
	{name = "tags", feed = true},
]

[languages.fr]
weight = 2
languageName = "Français"
languageCode = "fr"

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = true

# If you use CSS mode, make sure to add two themes - one for light mode,
# one for dark mode. In particular, hl-dark.css and hl-light.css are the
# default names. If you wish to use different names, see [extra.colors].
highlight_theme = "css"
highlight_themes_css = [
	{ theme = "agola-dark", filename = "hl-dark.css" },
	{ theme = "idle", filename = "hl-light.css" }
]

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

[extra]
# Stuff inherited from anemone
favicon = "favicon.ico"
twitter_card = true

# Default theme when people join the site. "dark" and "light" are the
# only valid values. By default, it's dark.
default_theme = "dark"

# Cursor logo, imported from hello-friend-ng
logo = { text = "> $ cd ~/zaaarf/" }
header_nav = [
	{ url = "/", name_en = "/home/", name_fr = "/accueil/" },
	{ url = "/about", name_en = "/about/", name_fr = "/concernant/" },
	{ url = "/journal", name_en = "/journal/", name_fr = "/journal/" },
	{ url = "/blog", name_en = "/blog/", name_fr = "/blog/" }
]

# Enable KaTeX for mathematical typesetting.
# Even if you enable it here, you still have to enable it on a per-page
# basis by setting setting extra.math to true.
enable_katex = false

# Homepage configuration stuff
[extra.home]
title = "you"
subtitle = "your subtitle"
subtitle_suffixes = [
	", this",
	", text",
	", is",
	", random!"
]

# You can fetch the subtitles from an API instead, setting these two parameters:
# random_api = "api.url" # url of the API
# random_api_param = "name" # parameter within the JSON to look at for
# I recommend https://git.alemi.dev/mood/ for this, in that case "mood" would the random_api_param,
# and the url would be wherever you set the endpoint to be.

# Social icons, list here: https://github.com/rhazdon/hugo-theme-hello-friend-ng/blob/master/layouts/partials/svg.html
social_icons = [
	{ name = "github", at = "https://github.com/zaaarf" },
	{ name = "codeberg", at = "https://codeberg.org/zaaarf" },
	{ name = "matrix", at = "https://matrix.to/#/@zaaarf:fantabos.co" },
	{ name = "discord", at = "@zaaarf", link = false },
	{ name = "email", at = "mailto:me@zaaarf.foo" }
]

# Valid keys are "post" and "list", one referring to individual blogposts,
# the other referring to lists of posts in sections.
# You may set "list" to whitespace(s) to disable displaying dates in sections.
# May be configured on section and page level as well.
# Refer to https://docs.rs/chrono/0.4.31/chrono/format/strftime/index.html
# for formatting instructions.
[extra.date_format]

# Theme customisation settings. Valid keys:
# - hightlighting: sets a custom CSS file for syntax highlighting. 
# - bgColor: used for the background.
# - fgColor: used for text.
# - metaColor: the "theme" color of the website, used for several things.
# - linkColor: used for links.
# - dateLinkColor: used for the date in the pagination, if enabled.
# - codeLineColor: used for the background of <code> blocks.
[extra.colors.dark]
meta_color = "#FF4D17"

[extra.colors.light]
meta_color = "#e08f67"
