name = "friendenstein"
description = "A somewhat minimalist Zola theme that strives to avoid JS as much as possible."
license = "MIT"
homepage = "https://git.fantabos.co/friendenstein.git"
min_version = "0.4.0"
# demo = "https://anemone.pages.dev"

[extra]


[author]
name = "zaaarf"
homepage = "https://zaaarf.foo/"
